## A Plot of Where Mosquitos Were Measured

```{r echo=FALSE, include=FALSE}
library(ggmap) # If you haven't yet, do this: install.packages("ggmap")  

data_dir <- "../input"
wnv <- read.csv(file.path(data_dir, "train.csv"))

# Ggmap is used to download and plot map images. Scripts don't have access to the network, so 
# the map data is included as an input file. 
# I downloaded it with the command: mapdata <- get_openstreetmap(bbox = c(-88.0, 41.6, -87.5, 42.1), color="bw", scale = round(606250/4))
mapdata <- readRDS(file.path(data_dir, "mapdata_copyright_openstreetmap_contributors.rds"))

```

Here's where we have measurement points for some date in the training data:

```{r}
# Shows where there are measurement points
ggmap(mapdata) + 
  geom_point(aes(x=Longitude, y=Latitude), data=wnv) +
  ggtitle("Mosquito Measurement Locations")
```


Measurement points with WMV detected in them in the training data:
```{r}
library(leaflet)
library(dplyr)

wnvPositive <- wnv[which(wnv$WnvPresent==1),]
wnvPositive$popup <- apply(wnvPositive,1,function(x){paste0(names(x),": ",x,collapse = "<BR>")})
m = leaflet(wnvPositive) %>% addTiles() %>% addMarkers(
  wnvPositive$Longitude, wnvPositive$Latitude, popup = wnvPositive$popup)
m
```

Polygon in which WMV was detected in them in the training data:
```{r}
library(leaflet)
library(dplyr)

wnvPositive <- wnv[which(wnv$WnvPresent==1),]
wnvNegative <- wnv[which(wnv$WnvPresent==0),]
chpositive <- wnvPositive[chull(wnvPositive$Longitude,wnvPositive$Latitude),]

chnegative <- wnvNegative[chull(wnvNegative$Longitude,wnvNegative$Latitude),]
m2 = leaflet(chnegative) %>% addTiles() %>% addPolygons(
  chnegative$Longitude, chnegative$Latitude,color = "blue") %>% addPolygons(
  chpositive$Longitude, chpositive$Latitude,color ="red")
m2
```


#Descriptive statistics

```{r}
numOfSamplesWithWNV <- length(which(wnv$WnvPresent == 1))